const columnTitleArray = [
  {
    id: "carStatus",
    label: "carStatus",
    key: "carStatus",
    title: "carStatus",
    type: "column",
  },
  {
    id: "carName",
    label: "carName",
    key: "carName",
    title: "carName",
    type: "column",
  },
  {
    id: "carCode",
    label: "carCode",
    key: "carCode",
    title: "carCode",
    type: "column",
  },
  {
    id: "plateNumber",
    label: "plateNumber",
    key: "plateNumber",
    title: "plateNumber",
    type: "column",
  },

  {
    id: "image",
    label: "image",
    key: "image",
    title: "image",
    type: "column",
  },
  {
    id: "cover",
    label: "cover",
    key: "cover",
    title: "cover",
    type: "column",
  },
  {
    id: "numberOfDoors",
    label: "numberOfDoors",
    key: "numberOfDoors",
    title: "numberOfDoors",
    type: "column",
  },
  {
    id: "numberOfPassengers",
    label: "numberOfPassengers",
    key: "numberOfPassengers",
    title: "numberOfPassengers",
    type: "column",
  },
  {
    id: "airCondition",
    label: "airCondition",
    key: "airCondition",
    title: "airCondition",
    type: "column",
  },
  {
    id: "showHome",
    label: "showHome",
    key: "showHome",
    title: "showHome",
    type: "column",
  },
  {
    id: "price",
    label: "price",
    key: "price",
    title: "price",
    type: "column",
  },
  {
    id: "offer",
    label: "offer",
    key: "offer",
    title: "offer",
    type: "column",
  },
  {
    id: "insurancePrice",
    label: "insurancePrice",
    key: "insurancePrice",
    title: "insurancePrice",
    type: "column",
  },
  {
    id: "dailyPrice",
    label: "dailyPrice",
    key: "dailyPrice",
    title: "dailyPrice",
    type: "column",
  },
  {
    id: "weeklyPrice",
    label: "weeklyPrice",
    key: "weeklyPrice",
    title: "weeklyPrice",
    type: "column",
  },
  {
    id: "monthlyPrice",
    label: "monthlyPrice",
    key: "monthlyPrice",
    title: "monthlyPrice",
    type: "column",
  },
  {
    id: "yearlyPrice",
    label: "yearlyPrice",
    key: "yearlyPrice",
    title: "yearlyPrice",
    type: "column",
  },
  {
    id: "offerDailyPrice",
    label: "offerDailyPrice",
    key: "offerDailyPrice",
    title: "offerDailyPrice",
    type: "column",
  },
  {
    id: "offerWeeklyPrice",
    label: "offerWeeklyPrice",
    key: "offerWeeklyPrice",
    title: "offerWeeklyPrice",
    type: "column",
  },
  {
    id: "offerMonthlyPrice",
    label: "offerMonthlyPrice",
    key: "offerMonthlyPrice",
    title: "offerMonthlyPrice",
    type: "column",
  },
  {
    id: "offerYearlyPrice",
    label: "offerYearlyPrice",
    key: "offerYearlyPrice",
    title: "offerYearlyPrice",
    type: "column",
  },
  {
    id: "kmPrice",
    label: "kmPrice",
    key: "kmPrice",
    title: "kmPrice",
    type: "column",
  },
  {
    id: "maxKm",
    label: "maxKm",
    key: "maxKm",
    title: "maxKm",
    type: "column",
  },

  {
    id: "notes",
    label: "notes",
    key: "notes",
    title: "notes",
    type: "column",
  },
  {
    id: "brandName",
    label: "brandName",
    key: "brandName",
    title: "brandName",
    type: "column",
  },
  {
    id: "brandArabicName",
    label: "brandArabicName",
    key: "brandArabicName",
    title: "brandArabicName",
    type: "column",
  },
  {
    id: "brandLogo",
    label: "brandLogo",
    key: "brandLogo",
    title: "brandLogo",
    type: "column",
  },

  {
    id: "modelEnglishName",
    label: "modelEnglishName",
    key: "modelEnglishName",
    title: "modelEnglishName",
    type: "column",
  },
  {
    id: "modelArabicName",
    label: "modelArabicName",
    key: "modelArabicName",
    title: "modelArabicName",
    type: "column",
  },

  {
    id: "engineEnglishName",
    label: "engineEnglishName",
    key: "engineEnglishName",
    title: "engineEnglishName",
    type: "column",
  },
  {
    id: "engineArabicName",
    label: "engineArabicName",
    key: "engineArabicName",
    title: "engineArabicName",
    type: "column",
  },

  {
    id: "carYear",
    label: "carYear",
    key: "carYear",
    title: "carYear",
    type: "column",
  },

  {
    id: "typeEnglishName",
    label: "typeEnglishName",
    key: "typeEnglishName",
    title: "typeEnglishName",
    type: "column",
  },
  {
    id: "typeArabicName",
    label: "typeArabicName",
    key: "typeArabicName",
    title: "typeArabicName",
    type: "column",
  },

  {
    id: "categoryEnglishName",
    label: "categoryEnglishName",
    key: "categoryEnglishName",
    title: "categoryEnglishName",
    type: "column",
  },
  {
    id: "categoryArabicName",
    label: "categoryArabicName",
    key: "categoryArabicName",
    title: "categoryArabicName",
    type: "column",
  },
  {
    id: "categoryDeliveryPrice",
    label: "categoryDeliveryPrice",
    key: "categoryDeliveryPrice",
    title: "categoryDeliveryPrice",
    type: "column",
  },

  {
    id: "finalPrice",
    label: "finalPrice",
    key: "finalPrice",
    title: "finalPrice",
    type: "column",
  },
  {
    id: "numOfDays",
    label: "numOfDays",
    key: "numOfDays",
    title: "numOfDays",
    type: "column",
  },
  {
    id: "datingType",
    label: "datingType",
    key: "datingType",
    title: "datingType",
    type: "column",
  },

  {
    id: "extraKm",
    label: "extraKm",
    key: "extraKm",
    title: "extraKm",
    type: "column",
  },
  {
    id: "extraPrice",
    label: "extraPrice",
    key: "extraPrice",
    title: "extraPrice",
    type: "column",
  },
];

export default columnTitleArray;
